### PR TITLE
feat: add pending option to QC status

### PR DESCRIPTION
**Pull request by dbirman**

### CODE REVIEW

**Comment by dbirman** [comment]
@jtyoung84 any insight about why the tests might be suddenly failing with this single-line addition? I can't get these failures to reproduce on my local python install.

**Comment by jtyoung84** [comment]
Which version of pydantic are you running locally? We don't have an upper bound, so github actions is using 2.9.0, which is pretty new.

**Comment by dbirman** [comment]
Yep that's it, runs fine on 2.8. Looks like there might be breaking changes in 2.9. I can make a separate PR to restrict to <=2.8 and open an issue for the upgrade?

**Comment by jtyoung84** [comment]
> Yep that's it, runs fine on 2.8. Looks like there might be breaking changes in 2.9. I can make a separate PR to restrict to <=2.8 and open an issue for the upgrade?

Maybe set it to <2.9?

**Review by saskiad — APPROVED** [review]

**Pull request merged**
