### PR TITLE
Reagent.source to Institution

### LINKED ISSUE #619: source in Reagent should be a PIDName
using Institutions?

### PR DESCRIPTION
**Pull request by Sun-flow**
closes #619 

Changing `Reagent.source` to take an `Institution` rather than a string.

### CODE REVIEW

**Comment by saskiad** [comment]
I might be second guessing this - give me a moment to think on this. Sorry for the fickleness

**Comment by saskiad** [comment]
I'm looking to merge Institution and Manufacturer into an "Organization" list that will better allow us to include Vendors, which is what we will want here. That's in PR #734 that is still in progress, but once that's done we can finish this up.

**Comment by saskiad** [comment]
this can be finished now - though given the amount of merge conflicts I expect it might be easier to start a new branch for this.

**Comment by Sun-flow** [comment]
This branch has become majorly outdated due to the deprecation of `Institution` in favor of `Organization`. Closing and writing a new PR + branch to cover the desired changes.

**Pull request closed without merging**
