### PR TITLE
Fix type signatures to be compatible with pydantic 2.9

### LINKED ISSUE #1050: Breaking changes in pydantic 2.9
One of several tests that fails if pydantic is updated to >=2.9

```
======================================================================
ERROR: tests.test_session (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_session
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/aind-data-schema/aind-data-schema/tests/test_session.py", line 19, in <module>
    from aind_data_schema.core.session import (
  File "/home/runner/work/aind-data-schema/aind-data-schema/src/aind_data_schema/core/session.py", line 42, in <module>
    from aind_data_schema.core.procedures import Anaesthetic, CoordinateReferenceLocation
  File "/home/runner/work/aind-data-schema/aind-data-schema/src/aind_data_schema/core/procedures.py", line 390, in <module>
    class Injection(AindModel):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 223, in __new__
    complete_model_class(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 568, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/main.py", line 670, in __get_pydantic_core_schema__
    return handler(source)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 924, in _generate_schema_inner
    return self._model_schema(obj)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 739, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 739, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1115, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1304, in _common_field_schema
    schema = self._apply_annotations(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2186, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2182, in <lambda>
    lambda source, handler: handler(source)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2093, in inner_handler
    return transform_inner_schema(schema)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1294, in set_discriminator
    schema = self._apply_discriminator_to_union(schema, field_info.discriminator)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 574, in _apply_discriminator_to_union
    return _discriminated_union.apply_discriminator(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_discriminated_union.py", line 97, in apply_discriminator
    return _ApplyInferredDiscriminator(discriminator, definitions or {}).apply(schema)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_discriminated_union.py", line 191, in apply
    schema = self._apply_to_root(schema)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_discriminated_union.py", line 227, in _apply_to_root
    self._handle_choice(choice)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_discriminated_union.py", line 289, in _handle_choice
    raise TypeError(
TypeError: 'list' is not a valid discriminated union variant; should be a `BaseModel` or `dataclass`
```

### PR DESCRIPTION
**Pull request by bruno-f-cruz**
Attempted to close #1050. However, the remaining error is really hard to fix at this point without major refactors to the unittest code base.

### CODE REVIEW

**Comment by bruno-f-cruz** [comment]
The final 2 failures I am not sure what is going on as I am not familiar what the tests and what they should be testing for. Perhaps someone can take a look?

Some files that I didn't touch are failing linting on my side:
`./aind-data-schema\src\aind_data_schema\core\quality_control.py`

**Comment by bruno-f-cruz** [comment]
The bug seems related with using `model_construct` to get empty classes. If a class has a required field the model construct will commit it from the output (In this case `ViralMaterial` and its respective `name` property`)

**Comment by dbirman** [comment]
I'm looking at this now and while I understand what the tests are supposed to do I *think* the issue might be coming from the use of model_construct all over the place? But fixing that would probably mean instantiating valid objects which seems like a pain as well. I'll look into pulling some valid objects from existing metadata perhaps.

**Comment by bruno-f-cruz** [comment]
> I'm looking at this now and while I understand what the tests are supposed to do I _think_ the issue might be coming from the use of model_construct all over the place? But fixing that would probably mean instantiating valid objects which seems like a pain as well. I'll look into pulling some valid objects from existing metadata perhaps.

Yep, as i said before (https://github.com/AllenNeuralDynamics/aind-data-schema/discussions/1033), relying on model_construct is probably not the best practice to follow, especially when combined with tagged unions. Tagged unions rely on a lot of behind-the-scenes validation that is skipped during model_construct, making their output somewhat brittle.

Regardless, the current PR should still be merged since it fixes other flagged bugs.

**Comment by dbirman** [comment]
Yes but there are still tests failing if I force pydantic to 2.9, so I'm trying to track those down

**Comment by dbirman** [comment]
Looping @mekhlakapoor and @jtyoung84 here, can you help me understand what [this test](https://github.com/AllenNeuralDynamics/aind-data-schema/blob/0104e43068841263aed63aacb46042b416e4b2c8/tests/test_metadata.py#L192) is doing and why it uses model_construct? Does this actually need to build a full Metadata object just to check whether injection_materials is missing?:

```
        # Tests missing injection materials
        surgery2 = Surgery.model_construct(procedures=[nano_inj])
        with self.assertRaises(ValueError) as context:
            Metadata(
                name="ecephys_655019_2023-04-03_18-17-09",
                location="bucket",
                data_description=DataDescription.model_construct(
                    label="some label", platform=Platform.ECEPHYS, creation_time=time(12, 12, 12)
                ),
                subject=Subject.model_construct(),
                procedures=Procedures.model_construct(subject_procedures=[surgery2]),
                rig=Rig.model_construct(),
                processing=Processing.model_construct(),
                session=Session.model_construct(),
            )
        self.assertIn("Injection is missing injection_materials.", str(context.exception))
```

If this is just testing whether injection_materials is missing, can I just replace it with a test that does 

```
        with self.assertRaises(ValidationError) as context:
            NanojectInjection(
                    protocol_id="5678",
                    recovery_time=0,
                    instrument_id=None,
                    injection_hemisphere="Left",
                    injection_coordinate_ml=-0.87,
                    injection_coordinate_ap=-3.8,
                    injection_coordinate_depth=[-3.3],
                    injection_coordinate_reference="Lambda",
                    bregma_to_lambda_distance=4.1,
                    injection_angle=10,
                    injection_volume=[200],
                    targeted_structure="VISp",
                )
        self.assertIn("1 validation error for NanojectInjection\ninjection_materials", str(context.exception))
```

Or even simpler just do the `self.assertRaises`?

The use of `model_construct` inside of these deep classes seems to cause new issues in Pydantic 2.9 and I think we need to avoid it when possible, and in general test with "real" objects.

**Review by dbirman — APPROVED** [review]

**Pull request merged**
