### PR TITLE
codespell: add config and action to codespell the code to avoid known typos

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by dyf** [comment]
@yarikoptic Thanks for this contribution! @jtyoung84 are you okay with where this action is, or do you want it somewhere else?

**Comment by jtyoung84** [comment]
> @yarikoptic Thanks for this contribution! @jtyoung84 are you okay with where this action is, or do you want it somewhere else?

Given our current workflows setup, it'd be nice to add codespell to the dev dependencies list in the pyproject.toml file and include running a check alongside the other checks in the ci.yml file.

**Comment by jtyoung84** [comment]
@yarikoptic If possible, can you open a PR into https://github.com/AllenNeuralDynamics/aind-data-schema/tree/enh-433-codespell? I can merge your suggestions and make a couple of minor updates before merging it into main. We appreciate your contributions. We're still sorting out our Contributor Guidelines. Cheers!

**Comment by yarikoptic** [comment]
I've changed the base to be that branch, didn't check if that is sufficiently close to main etc.

**Pull request merged**
