### PR TITLE
feat: adds schema_version attribute

### LINKED ISSUE #152: Add schema_version as attribute to AindCoreModel
# User story
As a developer, I want AindCoreModel to have a black attribute called schema_version, so I don't get warnings when accessing the schema_version attribute.

# Acceptance criteria
- [ ] AindCoreModel should have a schema_version attribute

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
I think the AindCoreModel is the parent class for the schemas that will eventually be used.

### PR DESCRIPTION
**Pull request by jtyoung84**
Closes #152

### CODE REVIEW

**Comment by jtyoung84** [comment]
Running
```
python -m aind_data_schema.utils.json_writer --output schemas --attach-version
```
will write the schemas out as something like:
```
schemas/subject/0.2.2/subject.json
```

**Review by dyf — APPROVED** [review]
good catch, thanks

**Comment by dyf** [comment]
didn't merge this b/c it's a draft - go ahead if you are done

**Comment by jtyoung84** [comment]
> didn't merge this b/c it's a draft - go ahead if you are done

@dyf I was hoping to include the push to the aws bucket in this pr, but I can open a new pr for that.

**Pull request merged**
