### PR TITLE
fix describedby inconsistencies

### LINKED ISSUE #67: check that describedBy points to the right repo

### PR DESCRIPTION
**Pull request by dyf**
resolves #67

### CODE REVIEW

**Comment by dyf** [comment]
@jtyoung84 , @mekhlakapoor I am experimenting with how to handle `describedBy` generically in one place.  I did this by creating a generic base class and doing some funky dynamic field generation.  Feedback welcome.

**Comment by jtyoung84** [comment]
> @jtyoung84 , @mekhlakapoor I am experimenting with how to handle `describedBy` generically in one place. I did this by creating a generic base class and doing some funky dynamic field generation. Feedback welcome.

A few unit tests would be cool.

**Comment by dyf** [comment]
> > @jtyoung84 , @mekhlakapoor I am experimenting with how to handle `describedBy` generically in one place. I did this by creating a generic base class and doing some funky dynamic field generation. Feedback welcome.
> 
> A few unit tests would be cool.

Yeah will do - mostly wanted to get a gut check for the dynamic typing approach.

**Comment by mekhlakapoor** [comment]
> > > @jtyoung84 , @mekhlakapoor I am experimenting with how to handle `describedBy` generically in one place. I did this by creating a generic base class and doing some funky dynamic field generation. Feedback welcome.
> > 
> > 
> > A few unit tests would be cool.
> 
> Yeah will do - mostly wanted to get a gut check for the dynamic typing approach.
> 
> Here:
> 
> https://github.com/AllenNeuralDynamics/aind-data-schema/blob/27bb22108067f6ea5e2192628787877b98aa5c3d/src/aind_data_schema/base.py#L14

I'm good with this approach

**Review by saskiad — APPROVED** [review]

**Pull request merged**
