### PR TITLE
anatomical coordinates and reference

### LINKED ISSUE #926: adding reference_manipulator_coordinates and target_manipulator_coordinates
**Is your feature request related to a problem? Please describe.**
We usually have two manipulator coordinates corresponding to the target and reference coordinates during the experiment. It's meaningless to have manipulator coordinates without providing the reference manipulator coordinates. Currently, we only have the `manipulator_coordinates` in the `session.py/ManipulatorModule`.
**Describe the solution you'd like**
Current
image

Suggested
image

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by saskiad**
closes #926

### CODE REVIEW

**Review by dyf — APPROVED** [review]
this is a breaking change, add a feat(xyz) to the squash commit message

**Comment by saskiad** [comment]
> this is a breaking change, add a feat(xyz) to the squash commit message

I don't know what you mean

**Comment by jtyoung84** [comment]
> this is a breaking change, add a feat(xyz) to the squash commit message

Since the additional fields are Optional, it shouldn't be a breaking change.

**Comment by jtyoung84** [comment]
Pulls in changes from https://github.com/AllenNeuralDynamics/aind-data-schema/pull/1013
Thanks @bruno-f-cruz !

**Pull request merged**
