### PR TITLE
make injection dv list

### PR DESCRIPTION
**Pull request by saskiad**

### CODE REVIEW

**Comment by saskiad** [comment]
closes #432

**Comment by saskiad** [comment]
we'll need a validator to assure that the length of DV coordinates and the length of injection volume match

**Comment by saskiad** [comment]
This will also impact how metadata service gets this info (e.g. the volume is one volume that is split between the two locations, so that math will need to be done)

**Comment by saskiad** [comment]
I don't understand this linter error. @jtyoung84 do you know what this is?

**Comment by dyf** [comment]
@saskiad fixed. @jtyoung84 looks like flake8 prefers to use `is` and `is not` for type comparisons now.

**Review by dyf — APPROVED** [review]

**Pull request merged**
