### PR TITLE
Refactor Calibration model to allow `Any`

### PR DESCRIPTION
**Pull request by bruno-f-cruz**
This PR:

- Refactors the Calibration class to allow "Any" types;
- Adds a water calibration model to the core schema.

Additionally, the follow example and script can be used to run unit tests, but I would like to know where you want me to drop it since the current tests do not seem to comtemplate tests for indivual 'AindModel' classes

```Python

from pydantic import PositiveFloat, PositiveInt, Field
from typing import List, Optional, Dict, Literal
from datetime import datetime
from aind_data_schema.base import AindModel
from aind_data_schema.models.devices import Calibration, WaterCalibration, WaterCalibrationInput, WaterCalibrationOutput
import json


_delta_times = [0.1, 0.2, 0.3, 0.4, 0.5]
_slope = 10.1
_offset = -0.3
_linear_model = (lambda time: _slope * time + _offset)
_water_weights = [_linear_model(x) for x in _delta_times]
_inputs = [
    WaterCalibrationInput(valve_open_interval=0.5, valve_open_time=t[0], water_weight=[t[1]], repeat_count=1)
    for t in zip(_delta_times, _water_weights)]

_outputs = WaterCalibrationOutput(
    interval_average={interval: volume for interval, volume in zip(_delta_times, _water_weights)},
    slope=_slope,
    offset=_offset,
    r2=1.0,
    valid_domain=[value for value in _delta_times])

calibration = WaterCalibration(
    input=_inputs,
    output=_outputs,
    device_name="WaterValve",
    calibration_date=datetime.now(),
    )

roundtrip = WaterCalibration.model_validate_json(calibration.model_dump_json())
roundtrip_parent = Calibration.model_validate_json(calibration.model_dump_json())


test = json.dumps(WaterCalibration.model_json_schema(), indent=3)
with open('test.json', "w") as f:
    f.write(test)

'''

### CODE REVIEW

**Comment by bruno-f-cruz** [comment]
Closes #692 
Discussed in #636

**Comment by saskiad** [comment]
We explicitly don't want a water calibration model. We want everythign to live in calibrations.

**Comment by bruno-f-cruz** [comment]
Ok after talking with @saskiad we have decided to move the water calibration model to a separate repo (https://github.com/AllenNeuralDynamics/aind-behavior-rig-calibration). I will try to keep all the calibration schemas here. The goal is to, in the future, subclass Calibration there.

I will refactor the PR to reflect this, but I would still want to keep the small change to the base class. In general I think we should review this pattern in the full aind-data-schema and move away from `Dict[str, any]` to `any` instead.

**Comment by bruno-f-cruz** [comment]
Closing this PR since it has been superseded bu #698

**Pull request closed without merging**
